# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "docling-project"
version = "0.1.0"

[tool.setuptools]
packages = [
    "app", 
    "cli", 
    "models", 
    "backend", 
    "yzhtest", 
    "chunking", 
    "pipeline", 
    "datamodel"
]